### ISSUE TITLE
Socials in footer

### ISSUE THREAD

**Issue by hnasheralneam** [zenith-hacks/website#18]
Leo made some social media accounts, we should put them on the page footer.

**Comment by hnasheralneam** [comment]
Account names should be on the Notion

**Comment by leowilkin** [comment]
https://zenith2025.notion.site/Contact-Cheatsheet-c6de8dc964db45b3a80e04d8c52bb204 here!

**Comment by hnasheralneam** [comment]
Fixed with this commit [65551e77e808ecbae6402198bb75d4d3ac04571a](https://github.com/zenith-hacks/website/commit/65551e77e808ecbae6402198bb75d4d3ac04571a)
